name: prototype_laundry
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/icon-removebg-preview.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/cuci_basah.jpg
    - lib/assets/images/cuci_kering.jpg
    - lib/assets/images/cuci_dan_setrika.jpg
    - lib/assets/images/cuci_karpet.jpg
    - lib/assets/images/Laundry.png
    - lib/assets/images/icon-removebg-preview.png

 